#makefile first lab

CC = gcc

CFLAGS = -g -Wall

# setup for sytsem

all: server1 client1

server1: server1.c
	$(CC) $(CFLAGS) server1.c -o server1

client1: client1.c
	$(CC) $(CFLAGS) client1.c -o client1

clean:
	rm server1, client1
